---
language: ruby
notifications:
  slack: bloomberg-rnd:eHp3Czg42iGzaTgG8sAFeD9v
env:
  matrix:
    - TEST=cookstyle
    - TEST="foodcritic ."
    - TEST="chef exec rspec"
before_install:
  - chef --version
  - eval "$(chef shell-init bash)"
  - cookstyle --version
  - foodcritic --version
install:
  - berks
script:
  - "$TEST"
rvm:
  - 2.2
cache:
  directories:
    - "$HOME/.berkshelf"
addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk
branches:
  only:
    - master
matrix:
  fast_finish: true
